config/routes.rb
Rails.application.routes.draw do
  get 'set_language/vietnames'

  get 'set_language/english'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", :locale => /en|vi/ do
    root 'static_pages#home'
    get '/admin' => 'sessions#new'
    post '/admin' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    get '/signup' => 'users#new'
    post '/users' => 'users#create'

    get '/content/new' => 'contents#new'
    post '/content/new' => 'contents#create'
    post '/contents' => 'contents#create'
    get '/contents/edit/:id' => 'contents#edit'
    post '/contents/edit/:id' => 'contents#update'
    get '/content' => 'contents#edit'
    get '/noi-dung/:content_id' => 'contents#show'
    delete '/contents/:content_id' => 'contents#destroy'

    get '/registrars' => 'registrars#index', as: :registrar

    get '/quan-ly' => 'managers#index'
    get '/dang-ky' => 'event#register'
    post '/dang-ky' => 'event#save'

    get '/sponsors' => 'sponsors#index'
    post '/sponsors' => 'sponsors#create'
    delete '/sponsors/:id' => 'sponsors#destroy'
    get '/news' => 'news#index'
    post '/news' => 'news#edit'

    get '/contents/:content_id/new' => 'contents#new_subcontent'
    post '/contents/:content_id/new' => 'contents#add_subcontent'
    get '/noi-dung/phu-luc/:id' => 'contents#show_subcontent'
    get '/subcontents/edit/:id' => 'contents#edit_subcontent'
    delete '/subcontents/:id' => 'contents#destroy_subcontent'
    post 'subcontents/edit/:id' => 'contents#update_subcontent'

    get '*path' => redirect("/")
  end
end

app/models/registrar.rb
class Registrar < ApplicationRecord
  mount_uploader :image, ContentUploader # Tells rails to use this uploader for this model.
  mount_uploader :cvs, CVUploader # Tells rails to use this uploader for this model.

  has_and_belongs_to_many :courses, through: :registrar_courses
end

app/controllers/registrars_controller.rb
class RegistrarsController < ApplicationController
  before_action :authorize

  def index
    @registrars = Registrar.all.paginate(page: params[:page], per_page: 20)
    @all_registrars = Registrar.all
    respond_to do |format|
      format.html
      format.xls
    end
  end
end

app/views/registrars/index.html.erb
<% if current_user %>
<div class="col-md-3">
  <div class="list-group">
    <a class="list-group-item" href="/"><i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp; Trang chủ</a>
    <a class="list-group-item" href="/quan-ly"><i class="fa fa-book fa-fw" aria-hidden="true"></i>&nbsp; Danh mục</a>
    <a class="list-group-item" href="/sponsors"><i class="fa fa-money fa-fw" aria-hidden="true"></i>&nbsp; Tài trợ</a>
    <a class="list-group-item active" href="/registrars"><i class="fa fa-list fa-fw" aria-hidden="true"></i>&nbsp; Danh sách đăng ký</a>
    <a class="list-group-item" href="/news"><i class="fa fa-newspaper-o fa-fw" aria-hidden="true"></i>&nbsp; News</a>
    <a class="list-group-item" href="/logout"><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>&nbsp; Đăng xuất</a>
  </div>
</div>
<div class="col-md-9">
  <div><%= link_to "Export excel", registrar_path(format: "xls") %></div>
  <table class = "table table-bordered table-striped">
    <thead>.
    <tr>
      <th>Họ và tên</th>
      <th>Ngày sinh</th>
	  <th>Quốc tịch</th>
	  <th>Cơ quan, tổ chức</th>
	  <th>Nghề nghiệp</th>
	  <th>Lĩnh vực hoạt động</th>
	  <th>Ảnh</th>
	  <th>CVs</th>
	  <th>Email</th>
	  <th>Số điện thoại</th>
    </tr>
    </thead>

    <tbody>
    <% @registrars.each do |registrar| %>
        <tr>
          <td><%= registrar.name %></td>
		  <td><%= registrar.birth %></td>
		  <td><%= registrar.nationality %></td>
		  <td><%= registrar.company %></td>
		  <td><%= registrar.job %></td>
		  <td><%= registrar.domain %></td>
          <td><%= link_to "Download", registrar.image.url %></td>
		  <td><%= link_to "Download", registrar.cvs.url %></td>
		  <td><%= registrar.email %></td>
		  <td><%= registrar.phone %></td>
        </tr>
    <% end %>
    </tbody>

  </table>

  <%= will_paginate @registrars, previous_label: 'Trước', next_label: 'Sau', renderer: BootstrapPagination::Rails %>
</div>

<% else %>
    <h1> Bạn phải <%= link_to "đăng nhập", "/admin" %> để xem được trang này</h1>
<% end %>

app/views/registrars/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell>
          <Data ss:Type="String">Họ và tên</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Ngày sinh</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Quốc tịch</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Cơ quan tổ chức</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Nghề nghiệp</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Lĩnh vực hoạt</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Email</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Số điện thoại</Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">Khóa học đã đăng ký</Data>
        </Cell>
      </Row>
      <% @all_registrars.each do |registrar| %>
          <Row>
            <Cell>
              <Data ss:Type="String"><%= registrar.name %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= registrar.birth %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= registrar.nationality %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= registrar.company %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= registrar.job %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= registrar.domain %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= registrar.email %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= registrar.phone %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><% if registrar.courses.length > 0 %><% registrar.courses.each do |course| %><%= course.name %>
                    <% end %>
                <% end %></Data>
            </Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>